Update CodeOSS CI

diff --git a/.github/workflows/codeoss-ci.yml b/.github/workflows/codeoss-ci.yml
--- a/.github/workflows/codeoss-ci.yml
+++ b/.github/workflows/codeoss-ci.yml
@@ -85,10 +85,70 @@ jobs:
         shell: bash
 
       - name: Switch to Terrapin packages
-        if: ${{ steps.restoreNodeModulesCache.outputs.cache-hit == 'true' }} && ${{ env.ENABLE_TERRAPIN }}
+        if: ${{ steps.restoreNodeModulesCache.outputs.cache-hit != 'true' }} && ${{ env.ENABLE_TERRAPIN }}
         run: |
           set -e
           npx https://aka.ms/enablesecurefeed standAlone
+        shell: bash
+
+      - name: Install build dependencies
+        run: |
+          set -e
+          for i in {1..3}; do # try 3 times, for Terrapin
+          	yarn --cwd build --frozen-lockfile && break
+          	if [ "$i" -eq 3 ]; then
+          		echo "Yarn failed too many times" >&2
+          		exit 1
+          	fi
+          	echo "Yarn failed $i, trying again..."
+          done
+        shell: bash
+
+      - name: Install dependencies
+        if: ${{ steps.restoreNodeModulesCache.outputs.cache-hit != 'true' }}
+        run: |
+          NPM_ARCH=${{ matrix.arch }}
+          [ "${{ matrix.arch }}" == "armhf" ] && NPM_ARCH=armv7l
+          echo "NPM_ARCH >>> $NPM_ARCH"
+          export NPM_ARCH
+
+          set -e
+          npm_config_arch=${NPM_ARCH}
+          export npm_config_arch
+
+          if [ -z "$CC" ] || [ -z "$CXX" ]; then
+          	# Download clang based on chromium revision used by vscode
+          	curl -s https://raw.githubusercontent.com/chromium/chromium/91.0.4472.164/tools/clang/scripts/update.py | python - --output-dir="$PWD"/.build/CR_Clang --host-os=linux
+          	# Download libcxx headers and objects from upstream electron releases
+          	DEBUG=libcxx-fetcher \
+          		VSCODE_LIBCXX_OBJECTS_DIR=$PWD/.build/libcxx-objects \
+          		VSCODE_LIBCXX_HEADERS_DIR=$PWD/.build/libcxx_headers \
+          		VSCODE_LIBCXXABI_HEADERS_DIR=$PWD/.build/libcxxabi_headers \
+          		VSCODE_ARCH="${NPM_ARCH}" \
+          		node build/linux/libcxx-fetcher.js
+          	# Set compiler toolchain
+          	# Flags for the client build are based on
+          	# https://source.chromium.org/chromium/chromium/src/+/refs/tags/91.0.4472.164:build/config/arm.gni
+          	# https://source.chromium.org/chromium/chromium/src/+/refs/tags/91.0.4472.164:build/config/compiler/BUILD.gn
+          	# https://source.chromium.org/chromium/chromium/src/+/refs/tags/91.0.4472.164:build/config/c++/BUILD.gn
+          	export CC=$PWD/.build/CR_Clang/bin/clang
+          	export CXX=$PWD/.build/CR_Clang/bin/clang++
+          	export CXXFLAGS="-nostdinc++ -D_LIBCPP_HAS_NO_VENDOR_AVAILABILITY_ANNOTATIONS -D__NO_INLINE__ -isystem$PWD/.build/libcxx_headers/include -isystem$PWD/.build/libcxxabi_headers/include -fPIC -flto=thin -fsplit-lto-unit"
+          	export LDFLAGS="-stdlib=libc++ -fuse-ld=lld -flto=thin -L$PWD/.build/libcxx-objects -lc++abi -Wl,--lto-O0"
+          	VSCODE_REMOTE_CC=$(which gcc)
+          	export VSCODE_REMOTE_CC
+          	VSCODE_REMOTE_CXX=$(which g++)
+          	export VSCODE_REMOTE_CXX
+          fi
+
+          for i in {1..3}; do # try 3 times, for Terrapin
+          	yarn --frozen-lockfile && break
+          	if [ $i -eq 3 ]; then
+          		echo "Yarn failed too many times" >&2
+          		exit 1
+          	fi
+          	echo "Yarn failed $i, trying again..."
+          done
         shell: bash
 
       - name: Build packages
