Sync build linux artifacts' configurations from `azure-pipelines`

diff --git a/.github/workflows/codeoss-ci.yml b/.github/workflows/codeoss-ci.yml
--- a/.github/workflows/codeoss-ci.yml
+++ b/.github/workflows/codeoss-ci.yml
@@ -19,7 +19,7 @@ env:
   PYTHON_VERSION: "3.x"
   CODE_ICO_URL: https://github.com/LiangchengJ/vscode/raw/94cba4eb314f52fd18b47b72459954fda65302d0/resources/win32/code.ico
   VSCODE_STEP_ON_IT: false
-  CACHE_VERSION: 1657204186
+  CACHE_VERSION: 1657207035
   PUBLISH_NAME: dev_test_part18
   PUBLISH_TAG_NAME: dev_test_part18
   PRE_RELEASE: true
@@ -221,14 +221,62 @@ jobs:
         id: cache-node-modules
         uses: actions/cache@v2
         with:
-          path: "**/node_modules"
+          path: ".build/node_modules_cache"
           key: "${{ runner.os }}NodeModules${{ steps.compute-node-modules-cache-key.outputs.key }}"
+
+      - name: Install build dependencies
+        run: |
+          node build/npm/setupBuildYarnrc
+          for i in {1..3}; do
+          	yarn --cwd build --frozen-lockfile --check-files && break
+          	if [ "$i" -eq 3 ]; then
+          		echo "Yarn failed too many times" >&2
+          		exit 1
+          	fi
+          	echo "Yarn failed $i, trying again..."
+          done
 
       - name: Install dependencies
         if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
         run: |
-          npm_config_arch=${NPM_ARCH}
+          if [ "$NPM_ARCH" = "armv7l" ]; then
+          	# There is no target_arch="armv7l" supported by node_gyp,
+          	# arm versions for compilation are decided based on the CC
+          	# macros.
+          	# Mapping value is based on
+          	# https://github.com/nodejs/node/blob/0903515e126c2697042d6546c6aa4b72e1a4b33e/configure.py#L49-L50
+          	npm_config_arch="arm"
+          else
+          	npm_config_arch=$NPM_ARCH
+          fi
           export npm_config_arch
+
+          if [ -z "$CC" ] || [ -z "$CXX" ]; then
+          	# Download clang based on chromium revision used by vscode
+          	curl -s https://raw.githubusercontent.com/chromium/chromium/98.0.4758.109/tools/clang/scripts/update.py |
+          		python - --output-dir="$PWD"/.build/CR_Clang --host-os=linux
+          	# Download libcxx headers and objects from upstream electron releases
+          	DEBUG=libcxx-fetcher \
+          		VSCODE_LIBCXX_OBJECTS_DIR=$PWD/.build/libcxx-objects \
+          		VSCODE_LIBCXX_HEADERS_DIR=$PWD/.build/libcxx_headers \
+          		VSCODE_LIBCXXABI_HEADERS_DIR=$PWD/.build/libcxxabi_headers \
+          		VSCODE_ARCH="$NPM_ARCH" \
+          		node build/linux/libcxx-fetcher.js
+          	# Set compiler toolchain
+          	# Flags for the client build are based on
+          	# https://source.chromium.org/chromium/chromium/src/+/refs/tags/98.0.4758.109:build/config/arm.gni
+          	# https://source.chromium.org/chromium/chromium/src/+/refs/tags/98.0.4758.109:build/config/compiler/BUILD.gn
+          	# https://source.chromium.org/chromium/chromium/src/+/refs/tags/98.0.4758.109:build/config/c++/BUILD.gn
+
+          	export CC="$PWD"/.build/CR_Clang/bin/clang
+          	export CXX="$PWD"/.build/CR_Clang/bin/clang++
+          	export CXXFLAGS="-nostdinc++ -D__NO_INLINE__ -isystem$PWD/.build/libcxx_headers -isystem$PWD/.build/libcxx_headers/include -isystem$PWD/.build/libcxxabi_headers/include -fPIC -flto=thin -fsplit-lto-unit"
+          	export LDFLAGS="-stdlib=libc++ -fuse-ld=lld -flto=thin -L$PWD/.build/libcxx-objects -lc++abi -Wl,--lto-O0"
+          	# shellcheck disable=SC2155
+          	export VSCODE_REMOTE_CC="$(which gcc)"
+          	# shellcheck disable=SC2155
+          	export VSCODE_REMOTE_CXX="$(which g++)"
+          fi
 
           for i in {1..3}; do
           	yarn --frozen-lockfile --check-files && break
@@ -241,6 +289,13 @@ jobs:
         env:
           ELECTRON_SKIP_BINARY_DOWNLOAD: 1
           PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
+
+      - name: Create node modules archive
+        if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
+        run: |
+          mkdir -p .build/node_modules_cache
+          node build/azure-pipelines/common/listNodeModules.js .build/node_modules_list.txt
+          tar -cJf .build/node_modules_cache/cache.tar.xz --files-from .build/node_modules_list.txt
 
       - name: Build client artifacts
         run: |
