Pre-release `dev_test_part24`

diff --git a/.github/workflows/codeoss-ci.yml b/.github/workflows/codeoss-ci.yml
--- a/.github/workflows/codeoss-ci.yml
+++ b/.github/workflows/codeoss-ci.yml
@@ -20,9 +20,9 @@ env:
   RUST_VERSION: 1.65.0
   CODE_ICO_URL: https://github.com/LcJuves/vscode/raw/94cba4eb314f52fd18b47b72459954fda65302d0/resources/win32/code.ico
   VSCODE_STEP_ON_IT: false
-  CACHE_VERSION: 1690813183
-  PUBLISH_NAME: dev_test_part23
-  PUBLISH_TAG_NAME: dev_test_part23
+  CACHE_VERSION: 1690888052
+  PUBLISH_NAME: dev_test_part24
+  PUBLISH_TAG_NAME: dev_test_part24
   PRE_RELEASE: true
 
 defaults:
@@ -120,14 +120,14 @@ jobs:
 
       - name: Compute node modules cache key
         id: compute-node-modules-cache-key
-        run: echo "key=$(node build/azure-pipelines/common/computeNodeModulesCacheKey.js $VSCODE_ARCH $CACHE_VERSION)" >>"$GITHUB_OUTPUT"
+        run: echo "key=$(node build/azure-pipelines/common/computeNodeModulesCacheKey.js compile)" >>"$GITHUB_OUTPUT"
 
       - name: Cache node modules
         id: cache-node-modules
         uses: actions/cache@v2
         with:
           path: ".build/node_modules_cache"
-          key: "${{ runner.os }}GenericNodeModules${{ steps.compute-node-modules-cache-key.outputs.key }}"
+          key: "${{ runner.os }}GenericNodeModules${{ steps.compute-node-modules-cache-key.outputs.key }}${{ env.CACHE_VERSION }}"
 
       - name: Extract node modules archive
         if: ${{ steps.cache-node-modules.outputs.cache-hit == 'true' }}
@@ -136,13 +136,13 @@ jobs:
       - name: Install dependencies
         if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
         run: |
-          for i in {1..3}; do
-          	yarn --frozen-lockfile --check-files && break
-          	if [ "$i" -eq 3 ]; then
-          		echo "Yarn failed too many times" >&2
-          		exit 1
-          	fi
-          	echo "Yarn failed $i, trying again..."
+          for i in {1..5}; do # try 5 times
+            yarn --frozen-lockfile --check-files && break
+            if [ "$i" -eq 3 ]; then
+              echo "Yarn failed too many times" >&2
+              exit 1
+            fi
+            echo "Yarn failed $i, trying again..."
           done
         env:
           ELECTRON_SKIP_BINARY_DOWNLOAD: 1
@@ -151,9 +151,14 @@ jobs:
       - name: Create node modules archive
         if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
         run: |
-          mkdir -p .build/node_modules_cache
           node build/azure-pipelines/common/listNodeModules.js .build/node_modules_list.txt
-          tar -cJf .build/node_modules_cache/cache.tar.xz --files-from .build/node_modules_list.txt
+          mkdir -p .build/node_modules_cache
+          tar -cJf .build/node_modules_cache/cache.tar.xz -T .build/node_modules_list.txt
+
+      - name: Check /build/ folder
+        run: yarn --cwd build compile && ./.github/workflows/check-clean-git-state.sh
+
+      - uses: ./install-builtin-extensions.yml
 
       - name: Compile & Hygiene
         run: yarn npm-run-all -lp core-ci-pr extensions-ci-pr hygiene eslint valid-layers-check vscode-dts-compile-check tsec-compile-check
@@ -184,7 +189,13 @@ jobs:
           tar -xvzf vscode-openssl-prebuilt-$OPENSSL_PREBUILT_VERSION.tgz --strip-components=2 -C openssl package/out/
 
       - name: Compress compilation artifact
-        run: tar -cvJ --ignore-failed-read -f compilation.tar.xz .build out-* test/integration/browser/out test/smoke/out test/automation/out openssl
+        run: |
+          tar -cvJ --ignore-failed-read \
+              --exclude='.build/node_modules_cache' \
+              --exclude='.build/node_modules_list.txt' \
+              --exclude='.build/distro' \
+              -f compilation.tar.xz \
+              .build out-* test/integration/browser/out test/smoke/out test/automation/out openssl
 
       - name: Publish compilation artifact
         uses: actions/upload-artifact@v3
@@ -261,14 +272,14 @@ jobs:
 
       - name: Compute node modules cache key
         id: compute-node-modules-cache-key
-        run: echo "key=$(node build/azure-pipelines/common/computeNodeModulesCacheKey.js $VSCODE_ARCH $CACHE_VERSION)" >>"$GITHUB_OUTPUT"
+        run: echo "key=$(node build/azure-pipelines/common/computeNodeModulesCacheKey.js linux $VSCODE_ARCH)" >>"$GITHUB_OUTPUT"
 
       - name: Cache node modules
         id: cache-node-modules
         uses: actions/cache@v2
         with:
           path: ".build/node_modules_cache"
-          key: "${{ runner.os }}NodeModules${{ steps.compute-node-modules-cache-key.outputs.key }}"
+          key: "${{ runner.os }}NodeModules${{ steps.compute-node-modules-cache-key.outputs.key }}${{ env.CACHE_VERSION }}"
 
       - name: Extract node modules archive
         if: ${{ steps.cache-node-modules.outputs.cache-hit == 'true' }}
@@ -346,6 +357,8 @@ jobs:
           mkdir -p .build/node_modules_cache
           node build/azure-pipelines/common/listNodeModules.js .build/node_modules_list.txt
           tar -cJf .build/node_modules_cache/cache.tar.xz --files-from .build/node_modules_list.txt
+
+      - uses: ./install-builtin-extensions.yml
 
       - name: Build client artifacts
         run: |
@@ -552,14 +565,14 @@ jobs:
 
       - name: Compute node modules cache key
         id: compute-node-modules-cache-key
-        run: echo "key=$(node build/azure-pipelines/common/computeNodeModulesCacheKey.js $VSCODE_ARCH $CACHE_VERSION)" >>"$GITHUB_OUTPUT"
+        run: echo "key=$(node build/azure-pipelines/common/computeNodeModulesCacheKey.js darwin $VSCODE_ARCH)" >>"$GITHUB_OUTPUT"
 
       - name: Cache node modules
         id: cache-node-modules
         uses: actions/cache@v2
         with:
           path: ".build/node_modules_cache"
-          key: "${{ runner.os }}NodeModules${{ steps.compute-node-modules-cache-key.outputs.key }}"
+          key: "${{ runner.os }}NodeModules${{ steps.compute-node-modules-cache-key.outputs.key }}${{ env.CACHE_VERSION }}"
 
       - name: Extract node modules archive
         if: ${{ steps.cache-node-modules.outputs.cache-hit == 'true' }}
@@ -568,13 +581,12 @@ jobs:
       - name: Install dependencies
         if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
         run: |
-          npm install -g node-gyp@latest
           npm_config_arch=$VSCODE_ARCH
           export npm_config_arch
           npm_config_node_gyp=$(which node-gyp)
           export npm_config_node_gyp
 
-          for i in {1..3}; do
+          for i in {1..5}; do # try 5 times
           	yarn --frozen-lockfile --check-files && break
           	if [ "$i" -eq 3 ]; then
           		echo "Yarn failed too many times" >&2
@@ -592,6 +604,8 @@ jobs:
           mkdir -p .build/node_modules_cache
           node build/azure-pipelines/common/listNodeModules.js .build/node_modules_list.txt
           tar -cJf .build/node_modules_cache/cache.tar.xz --files-from .build/node_modules_list.txt
+
+      - uses: ./install-builtin-extensions.yml
 
       - name: Build client artifacts
         run: |
@@ -683,46 +697,18 @@ jobs:
 
       - name: Compute node modules cache key
         id: compute-node-modules-cache-key
-        run: echo "key=$(node build/azure-pipelines/common/computeNodeModulesCacheKey.js $VSCODE_ARCH $CACHE_VERSION)" >>"$GITHUB_OUTPUT"
+        run: echo "key=$(node build/azure-pipelines/common/computeNodeModulesCacheKey.js darwin x64)" >>"$GITHUB_OUTPUT"
 
       - name: Cache node modules
         id: cache-node-modules
         uses: actions/cache@v2
         with:
           path: ".build/node_modules_cache"
-          key: "${{ runner.os }}NodeModules${{ steps.compute-node-modules-cache-key.outputs.key }}"
+          key: "${{ runner.os }}NodeModules${{ steps.compute-node-modules-cache-key.outputs.key }}${{ env.CACHE_VERSION }}"
 
       - name: Extract node modules archive
         if: ${{ steps.cache-node-modules.outputs.cache-hit == 'true' }}
         run: tar -xJf .build/node_modules_cache/cache.tar.xz
-
-      - name: Install dependencies
-        if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
-        run: |
-          npm install -g node-gyp@latest
-          npm_config_arch=$VSCODE_ARCH
-          export npm_config_arch
-          npm_config_node_gyp=$(which node-gyp)
-          export npm_config_node_gyp
-
-          for i in {1..3}; do
-          	yarn --frozen-lockfile --check-files && break
-          	if [ "$i" -eq 3 ]; then
-          		echo "Yarn failed too many times" >&2
-          		exit 1
-          	fi
-          	echo "Yarn failed $i, trying again..."
-          done
-        env:
-          ELECTRON_SKIP_BINARY_DOWNLOAD: 1
-          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
-
-      - name: Create node modules archive
-        if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
-        run: |
-          mkdir -p .build/node_modules_cache
-          node build/azure-pipelines/common/listNodeModules.js .build/node_modules_list.txt
-          tar -cJf .build/node_modules_cache/cache.tar.xz --files-from .build/node_modules_list.txt
 
       - name: Create Universal App
         run: |
@@ -825,14 +811,14 @@ jobs:
 
       - name: Compute node modules cache key
         id: compute-node-modules-cache-key
-        run: echo "key=$(node build/azure-pipelines/common/computeNodeModulesCacheKey.js $VSCODE_ARCH $CACHE_VERSION)" >>"$GITHUB_OUTPUT"
+        run: echo "key=$(node build/azure-pipelines/common/computeNodeModulesCacheKey.js win32 $VSCODE_ARCH)" >>"$GITHUB_OUTPUT"
 
       - name: Cache node modules
         id: cache-node-modules
         uses: actions/cache@v2
         with:
           path: ".build/node_modules_cache"
-          key: "${{ runner.os }}NodeModules${{ steps.compute-node-modules-cache-key.outputs.key }}"
+          key: "${{ runner.os }}NodeModules${{ steps.compute-node-modules-cache-key.outputs.key }}${{ env.CACHE_VERSION }}"
 
       - name: Extract node modules archive
         if: ${{ steps.cache-node-modules.outputs.cache-hit == 'true' }}
@@ -864,6 +850,19 @@ jobs:
           mkdir -p .build/node_modules_cache
           node build/azure-pipelines/common/listNodeModules.js .build/node_modules_list.txt
           tar -cJf .build/node_modules_cache/cache.tar.xz --files-from .build/node_modules_list.txt
+
+      - uses: ./install-builtin-extensions.yml
+
+      - name: Generate Group Policy definitions
+        run: |
+          for i in {1..3}; do
+            node build\lib\policies && break
+            if [ "$i" -eq 3 ]; then
+              echo "Generating group policy failed too many times" >&2
+              exit 1
+            fi
+            echo "Generating group policy failed $i, trying again..."
+          done
 
       - name: Build client artifacts
         run: |
