Sync build linux artifacts' configurations from `azure-pipelines`

diff --git a/.github/workflows/codeoss-ci.yml b/.github/workflows/codeoss-ci.yml
--- a/.github/workflows/codeoss-ci.yml
+++ b/.github/workflows/codeoss-ci.yml
@@ -19,7 +19,7 @@ env:
   PYTHON_VERSION: "3.x"
   CODE_ICO_URL: https://github.com/LiangchengJ/vscode/raw/94cba4eb314f52fd18b47b72459954fda65302d0/resources/win32/code.ico
   VSCODE_STEP_ON_IT: false
-  CACHE_VERSION: 1657207035
+  CACHE_VERSION: 1657208264
   PUBLISH_NAME: dev_test_part18
   PUBLISH_TAG_NAME: dev_test_part18
   PRE_RELEASE: true
@@ -123,15 +123,34 @@ jobs:
         id: cache-node-modules
         uses: actions/cache@v2
         with:
-          path: "**/node_modules"
+          path: ".build/node_modules_cache"
           key: "${{ runner.os }}GenericNodeModules${{ steps.compute-node-modules-cache-key.outputs.key }}"
+
+      - name: Extract node modules archive
+        if: ${{ steps.cache-node-modules.outputs.cache-hit == 'true' }}
+        run: tar -xJf .build/node_modules_cache/cache.tar.xz
 
       - name: Install dependencies
         if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
-        run: yarn --frozen-lockfile --check-files --network-timeout 180000
+        run: |
+          for i in {1..3}; do
+          	yarn --frozen-lockfile --check-files && break
+          	if [ "$i" -eq 3 ]; then
+          		echo "Yarn failed too many times" >&2
+          		exit 1
+          	fi
+          	echo "Yarn failed $i, trying again..."
+          done
         env:
           ELECTRON_SKIP_BINARY_DOWNLOAD: 1
           PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
+
+      - name: Create node modules archive
+        if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
+        run: |
+          mkdir -p .build/node_modules_cache
+          node build/azure-pipelines/common/listNodeModules.js .build/node_modules_list.txt
+          tar -cJf .build/node_modules_cache/cache.tar.xz --files-from .build/node_modules_list.txt
 
       - name: Compile & Hygiene
         run: yarn npm-run-all -lp core-ci extensions-ci hygiene eslint valid-layers-check
@@ -154,6 +173,8 @@ jobs:
   build-for-linux:
     name: Build for Linux
     runs-on: ubuntu-latest
+    env:
+      DISPLAY: ":10"
     container:
       image: vscodehub.azurecr.io/vscode-linux-build-agent:${{ matrix.image-tag }}
       volumes:
@@ -197,10 +218,7 @@ jobs:
         if: ${{ env.VSCODE_ARCH == 'x64' }}
         run: |
           # Start X server
-          sudo cp build/azure-pipelines/linux/xvfb.init /etc/init.d/xvfb
-          sudo chmod +x /etc/init.d/xvfb
-          sudo update-rc.d xvfb defaults
-          sudo service xvfb start
+          /etc/init.d/xvfb start
           # Start dbus session
           DBUS_LAUNCH_RESULT=$(sudo dbus-daemon --config-file=/usr/share/dbus-1/system.conf --print-address)
           echo "DBUS_SESSION_BUS_ADDRESS=$DBUS_LAUNCH_RESULT" >>"$GITHUB_ENV"
@@ -223,6 +241,10 @@ jobs:
         with:
           path: ".build/node_modules_cache"
           key: "${{ runner.os }}NodeModules${{ steps.compute-node-modules-cache-key.outputs.key }}"
+
+      - name: Extract node modules archive
+        if: ${{ steps.cache-node-modules.outputs.cache-hit == 'true' }}
+        run: tar -xJf .build/node_modules_cache/cache.tar.xz
 
       - name: Install build dependencies
         run: |
