Update CodeOSS CI

diff --git a/.github/workflows/codeoss-ci.yml b/.github/workflows/codeoss-ci.yml
--- a/.github/workflows/codeoss-ci.yml
+++ b/.github/workflows/codeoss-ci.yml
@@ -19,6 +19,8 @@ env:
   PYTHON_VERSION: "2.x"
   SPLIT_LINE: =============================
   CODE_ICO_URL: https://raw.githubusercontent.com/LiangchengJ/vscode/94cba4eb314f52fd18b47b72459954fda65302d0/resources/win32/code.ico
+  ENABLE_TERRAPIN: true
+  VSCODE_STEP_ON_IT: false
 
 jobs:
   generate-product-configurations:
@@ -61,10 +63,129 @@ jobs:
           echo "::set-output name=version::$VERSION"
         shell: bash
 
+  compile:
+    name: Compile
+    runs-on: ubuntu-latest
+    needs: generate-product-configurations
+
+    steps:
+      - uses: actions/checkout@v2
+      - uses: actions/setup-node@v2
+        with:
+          node-version: ${{ env.NODE_VERSION }}
+      - name: Update product configurations
+        run: |
+          echo '${{ needs.generate-product-configurations.outputs.product-json }}' >product.json
+          NPM_ARCH=${{ matrix.arch }}
+          [ "${NPM_ARCH}" == "armhf" ] && NPM_ARCH=armv7l
+          echo "NPM_ARCH=$NPM_ARCH" >>"$GITHUB_ENV"
+          echo "VSCODE_ARCH=${{ matrix.arch }}" >>"$GITHUB_ENV"
+          VSCODE_QUALITY=$(node -p "require('./product.json')['quality']||''")
+          echo "VSCODE_QUALITY=$VSCODE_QUALITY" >>"$GITHUB_ENV"
+          APPLICATION_NAME=$(node -p "require('./product.json')['applicationName']")
+          echo "APPLICATION_NAME=$APPLICATION_NAME" >>"$GITHUB_ENV"
+        shell: bash
+
+      - name: Prepare yarn cache flags
+        id: prepareYarnCacheFlags
+        run: |
+          mkdir -p .build
+          node build/azure-pipelines/common/computeNodeModulesCacheKey.js $VSCODE_ARCH $ENABLE_TERRAPIN >.build/yarnlockhash
+          echo "::set-output name=yarnlockhash::$(cat .build/yarnlockhash)"
+        shell: bash
+
+      - name: Restore node_modules cache
+        id: restoreNodeModulesCache
+        uses: actions/cache@v2
+        with:
+          path: ".build/node_modules_cache"
+          key: "${{ runner.os }}-genericNodeModules-${{ steps.prepareYarnCacheFlags.outputs.yarnlockhash }}"
+
+      - name: Extract node_modules cache
+        if: ${{ steps.restoreNodeModulesCache.outputs.cache-hit == 'true' }}
+        run: |
+          set -e
+          tar -xzf .build/node_modules_cache/cache.tgz
+        shell: bash
+
+      - name: Switch to Terrapin packages
+        if: ${{ steps.restoreNodeModulesCache.outputs.cache-hit != 'true' }} && ${{ env.ENABLE_TERRAPIN }}
+        run: |
+          set -e
+          npx https://aka.ms/enablesecurefeed standAlone
+        shell: bash
+
+      - name: Install build tools
+        if: ${{ steps.restoreNodeModulesCache.outputs.cache-hit != 'true' }}
+        run: |
+          set -e
+          sudo apt update -y
+          sudo apt install -y build-essential pkg-config libx11-dev libx11-xcb-dev libxkbfile-dev libsecret-1-dev libnotify-bin
+        shell: bash
+
+      - name: Install dependencies
+        if: ${{ steps.restoreNodeModulesCache.outputs.cache-hit != 'true' }}
+        run: |
+          set -e
+          for i in {1..3}; do # try 3 times, for Terrapin
+          	yarn --frozen-lockfile && break
+          	if [ "$i" -eq 3 ]; then
+          		echo "Yarn failed too many times" >&2
+          		exit 1
+          	fi
+          	echo "Yarn failed $i, trying again..."
+          done
+        env:
+          ELECTRON_SKIP_BINARY_DOWNLOAD: 1
+          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
+        shell: bash
+
+      - name: Create node_modules archive
+        if: ${{ steps.restoreNodeModulesCache.outputs.cache-hit != 'true' }}
+        run: |
+          set -e
+          node build/azure-pipelines/common/listNodeModules.js .build/node_modules_list.txt
+          mkdir -p .build/node_modules_cache
+          tar -czf .build/node_modules_cache/cache.tgz --files-from .build/node_modules_list.txt
+        shell: bash
+
+      # Mixin must run before optimize, because the CSS loader will inline small SVGs
+      - name: Mix in quality
+        run: |
+          set -e
+          node build/azure-pipelines/mixin
+        shell: bash
+
+      - name: Compile & Hygiene
+        run: |
+          set -e
+          yarn npm-run-all -lp core-ci extensions-ci hygiene eslint valid-layers-check
+        shell: bash
+
+      - name: Compile test suites
+        if: ${{ env.VSCODE_STEP_ON_IT == false }}
+        run: |
+          set -e
+          yarn --cwd test/smoke compile
+          yarn --cwd test/integration/browser compile
+        shell: bash
+
+      - name: Compress compilation artifact
+        run: |
+          set -e
+          tar -cz --ignore-failed-read -f compilation.tar.gz .build out-* test/integration/browser/out test/smoke/out test/automation/out
+        shell: bash
+
+      - name: Publish compilation artifact
+        uses: actions/upload-artifact@v3
+        with:
+          name: Compilation
+          path: compilation.tar.gz
+
   linux:
     name: Linux
     runs-on: ubuntu-latest
-    needs: generate-product-configurations
+    needs: [generate-product-configurations, compile]
     strategy:
       matrix:
         arch: [x64, arm64, armhf]
@@ -167,8 +288,8 @@ jobs:
           echo "XZ_TARBALL_NAME=$XZ_TARBALL_NAME" >>"$GITHUB_ENV"
           echo "::set-output name=xz-tarball-name::$XZ_TARBALL_NAME"
           [ -z "${VSCODE_QUALITY}" ] &&
-          	GZ_TARBALL_NAME="${APPLICATION_NAME}-${VSCODE_ARCH}-$BUILD_VERSION.tar.gz" ||
-          	GZ_TARBALL_NAME="${APPLICATION_NAME}-${VSCODE_QUALITY}-${VSCODE_ARCH}-$BUILD_VERSION.tar.gz"
+          	GZ_TARBALL_NAME="code-${VSCODE_ARCH}-$BUILD_VERSION.tar.gz" ||
+          	GZ_TARBALL_NAME="code-${VSCODE_QUALITY}-${VSCODE_ARCH}-$BUILD_VERSION.tar.gz"
           echo "GZ_TARBALL_NAME=$GZ_TARBALL_NAME" >>"$GITHUB_ENV"
           echo "::set-output name=gz-tarball-name::$GZ_TARBALL_NAME"
 
